# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'singedin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


# from singedin1 import Ui_Form


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 540)       # form Window Size

        # Logout
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(290, 180, 175, 23))
        self.pushButton.setObjectName("pushButton")

        # Label
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 90, 1000, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.pushButton.clicked.connect(lambda: self.addData(Form))
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def addData(self, Mai):
        print("Got you! Everything is working fine")

        from s1 import Ui_MainWindow
        self.MainWindow = QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        Mai.hide()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Logged In"))
        self.pushButton.setText(_translate("Form", "logout"))
        self.label.setText(_translate("Form", "Hey Ankita its working now! You have successfully Logged in"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Form1()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
